// <auto-generated />
using System;
using BookingService.Infrastructure.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingService.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20241017233057_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DiscountTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPersonalized")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DiscountTypeId");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.DiscountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DiscountTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50eaddfb-453e-4659-9eda-6db327866727"),
                            IsDeleted = false,
                            Name = "Percentage"
                        },
                        new
                        {
                            Id = new Guid("3b814b2a-78be-4258-86b7-5e28748512ea"),
                            IsDeleted = false,
                            Name = "Quantitative"
                        });
                });

            modelBuilder.Entity("BookingService.Domain.Entities.SeatType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PriceMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SeatTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f86e1e1-0a7c-49d7-a1b9-f2b22c4b397d"),
                            IsDeleted = false,
                            Name = "Standard",
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = new Guid("a3be1280-f68e-4cd0-9b76-e0e80ce3e171"),
                            IsDeleted = false,
                            Name = "Comfort",
                            PriceMultiplier = 1.4m
                        },
                        new
                        {
                            Id = new Guid("6751ee97-937c-495b-8fd1-21ee831abb51"),
                            IsDeleted = false,
                            Name = "Business",
                            PriceMultiplier = 2.0m
                        });
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("SeatTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId", "TripId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.TicketStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TicketStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d7923cd-18e5-4079-a923-fd6b4161669e"),
                            IsDeleted = false,
                            Name = "Booked"
                        },
                        new
                        {
                            Id = new Guid("e5205282-f372-4cdd-b07f-8b13ad0423a8"),
                            IsDeleted = false,
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = new Guid("09bb0827-2a26-4fbd-af34-038ba7ce854e"),
                            IsDeleted = false,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("DepartureCity", "ArrivalCity", "DepartureTime");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.TripSeatAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeatsAvailable")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeatTypeId");

                    b.HasIndex("TripId", "SeatTypeId")
                        .IsUnique();

                    b.ToTable("TripSeatAvailabilities", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.TripType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TripTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("edfcc57a-cf58-4e5f-bbf2-f8b4d501b4ce"),
                            IsDeleted = false,
                            Name = "Airplane"
                        },
                        new
                        {
                            Id = new Guid("90ef03ce-fa58-4e6d-abff-9fca12ae598a"),
                            IsDeleted = false,
                            Name = "Train"
                        });
                });

            modelBuilder.Entity("BookingService.Domain.Entities.UserCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounponId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CounponId");

                    b.HasIndex("UserId", "CounponId")
                        .IsUnique();

                    b.ToTable("UserCoupons", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Coupon", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.DiscountType", null)
                        .WithMany()
                        .HasForeignKey("DiscountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Domain.Entities.SeatType", null)
                        .WithMany()
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Domain.Entities.TicketStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Trip", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.TripType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingService.Domain.Entities.TripSeatAvailability", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.SeatType", null)
                        .WithMany()
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingService.Domain.Entities.UserCoupon", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CounponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
